previewsEnabled: false
services:
  - type: web
    plan: free
    env: docker
    name: rq-worker
    runtime: image
    image:
     url: dalongrong/rq-worker:x-v9
    envVars: 
       - fromGroup: RQ
